language: python

python:
  - 2.7
  - 3.6

env:
  - DJANGO=1.10
  - DJANGO=1.11

install:
  - pip install -r requirements.txt
  - pip install coverage django-nose coveralls

script:
  - cd tests && coverage run manage.py test && mv .coverage ../ && cd ..

notifications:
    email:
      - martyn.clement@gmail.com

after_success:
  - coveralls
