language: python

python:
  - 2.7
  - 3.6

env:
  - DJANGO=1.10
  - DJANGO=1.11

install:
  - pip install -r requirements.txt
  - pip install coverage django-nose coveralls

script:
  - coverage run tests/manage.py test

notifications:
    email:
      - martyn@engage-sports.com

after_success:
  - coveralls
